feat(src): add src
Saebasol/heliotrope-web-downloader pull request #2
Opened 2021-01-08 16:52 UTC by SaidBySolo

2021-01-08 20:04 UTC, Seia-Soto commented on src/App.jsx
> +import React, { useState, useEffect } from 'react'
CJS 형태가 아닌 ESM 형태로 React 사용

```
import * as React from 'react'`

...

const { useState } = React
```

2021-01-08 20:05 UTC, Seia-Soto commented on src/App.jsx
> +    Promise.all(downloadImage).then(() =>
Async 블록 안에서 async/await 키워드 사용

```js
await Promise.all
```

2021-01-08 20:06 UTC, Seia-Soto commented on src/App.jsx
> +  const [data, setData] = useState(0)
변수명 사용 유의

2021-01-08 20:07 UTC, Seia-Soto commented on src/App.jsx
> +
빈줄 삭제

2021-01-08 20:07 UTC, Seia-Soto commented on src/App.jsx
> +    const imageInfoResponse = await fetch('https://doujinshiman.ga/v3/api/hitomi/images/1', { headers })
API 주소 동적으로 변경될 수 있도록 프로젝트에 api.js 추가 바람.=

2021-01-08 20:08 UTC, Seia-Soto commented on src/index.css
> +  -moz-osx-font-smoothing: grayscale;
가능한 경우 CSS 외부 라이브러리 사용해서 다른 플랫폼까지 자동적으로 컴파일 및 CSSReset/Normalize 사용 권장

2021-01-08 20:09 UTC, Seia-Soto commented on src/App.jsx
> +function App() {
Named function이 필요하지 않은 이상 화살표 함수 사용 및 props를 기본 인자로 등록

2021-01-08 20:09 UTC, Seia-Soto commented on src/index.jsx
> +import React from 'react';
CJS 형태가 아닌 ESM 형태로 React 사용

```
import * as React from 'react'`

...

const { useState } = React
```

2021-01-08 20:11 UTC, Seia-Soto requested changes, later dismissed
Please, change lines as I comment for better maintain in future.

2021-04-15 07:33 UTC, sannoob commented on src/App.jsx
> +        zip.generateAsync({ type: 'blob' })
async function에서 then 사용은 await 으로 통일하는 것이 좋아 보입니다

2021-04-15 07:34 UTC, sannoob submitted a review, later dismissed
Async function에서 then을 await 으로 변경

2021-04-15 15:43 UTC, Seia-Soto commented on src/App.jsx
> +    if (!downloadIndex || !Number.isInteger(parseInt(downloadIndex))) {
isNaN 함수 활용 시도

2021-04-15 15:43 UTC, Seia-Soto commented on src/App.jsx
> +    if (window.confirm("언어의 한계로 많은 이미지는 다운로드 할수 없을수도 있습니다. 시도하시겠습니까?")) {
언어의 한계?

2021-04-15 15:46 UTC, SaidBySolo commented on src/App.jsx
> +    if (window.confirm("언어의 한계로 많은 이미지는 다운로드 할수 없을수도 있습니다. 시도하시겠습니까?")) {
아 정확힌 브라우저의 한계네요 수정할게욤

2021-04-21 15:44 UTC, Seia-Soto commented
그래서 이거 언제 끝나요

2021-04-21 15:44 UTC, SaidBySolo commented
approve 뜰때까지요

2021-04-21 22:20 UTC, merged